global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#alert'
